### ISSUE TITLE
Password table

### ISSUE THREAD

**Issue by factorypattern99** [devkabir/wordpress-plugin-management-system#5]
### Discussed in https://github.com/devkabir/wordpress-plugin-management-system/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **factorypattern99** June 30, 2023</sup>
Hi, I can't seem to find the database table for the username and password to login to the app, could you please advise?</div>

**Comment by devkabir** [comment]
Migration Path: database/migrations/2014_10_12_000000_create_users_table.php
Seeder: database/seeders/DatabaseSeeder.php:17

**Comment by devkabir** [comment]
@factorypattern99 please review [this](https://filamentphp.com/docs/2.x/admin/installation#installation:~:text=If%20you%20don%27t%20have%20one%2C%20you%20may%20create%20a%20new%20user%20account%20using%3A) for more.
